name: tinyml
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - expat=2.7.3=h885b0b7_4
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - mkl=2025.3.0=hac47afa_455
  - numpy=2.2.6=py310h4987827_0
  - openssl=3.6.0=h725018a_0
  - pandas=2.3.3=py310hed136d8_2
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - audioread==3.1.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - decorator==5.2.1
      - filelock==3.20.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - msgpack==1.1.2
      - narwhals==2.15.0
      - networkx==3.4.2
      - numba==0.63.1
      - packaging==25.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - protobuf==6.33.4
      - pyarrow==23.0.0
      - pycparser==2.23
      - pydeck==0.9.1
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - smmap==5.0.2
      - soundfile==0.13.1
      - soxr==1.0.0
      - streamlit==1.53.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1+cpu
      - torchaudio==2.9.1+cpu
      - tornado==6.5.4
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - watchdog==6.0.0
prefix: C:\Users\Vibhav\miniconda3\envs\tinyml
